#!/usr/bin/env bash
set -ex

INPUT=$(realpath $1)
OUTPUT=$(realpath $2)
VERSION=$3

INPUT_NAME=$(basename -- "$INPUT")

TARBALL="${INPUT_NAME}_${VERSION}"

rm -rf $OUTPUT/$TARBALL
git clone -q $INPUT $OUTPUT/$TARBALL
rm -rf $OUTPUT/$TARBALL/.git

cd $INPUT
git describe --dirty --always --match __EXCLUDE__ --abbrev=7 > $OUTPUT/$TARBALL/__git__
TZ=UTC git log -1 --date=iso --pretty=format:%cd >> $OUTPUT/$TARBALL/__git__

# Inspired from https://stackoverflow.com/a/246128
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

bash $SCRIPT_DIR/_utils/create_reproducible_tarball.sh $OUTPUT/$TARBALL $INPUT
