change-id = 134650

[build]
extended = true
tools = ["cargo"]
full-bootstrap = true

rustc = "/rustbuilder/bin/rustc"
cargo = "/rustbuilder/bin/cargo"

[llvm]
download-ci-llvm = false
ninja = false
libzstd = true

[rust]
jemalloc = true
use-lld = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker = "/distroot/bin/clang"
ar = "/distroot/bin/llvm-ar"
ranlib = "/distroot/bin/llvm-ranlib"
