change-id = 134650

[build]
build-stage = 2
extended = true
tools = ["cargo"]
full-bootstrap = true

[llvm]
download-ci-llvm = false
ninja = false
libzstd = true

[rust]
jemalloc = true
use-lld = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker = "/distroot/bin/clang"
ar = "/distroot/bin/llvm-ar"
ranlib = "/distroot/bin/llvm-ranlib"
